project_id = "ksycnwwgpyulnkfvzqwm"

[functions.get-upload-url]
verify_jwt = false

[functions.complete-upload]
verify_jwt = false

[functions.upload-media]
verify_jwt = false

[functions.admin-login]
verify_jwt = false
