// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksycnwwgpyulnkfvzqwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzeWNud3dncHl1bG5rZnZ6cXdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MzcyNDksImV4cCI6MjA3NDIxMzI0OX0.SXJG-vD0D3zVnl8lgeRP3m7XoGNMUQ1xvObsVS7HESA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});